// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdxqfwpkdvekydozjzlm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkeHFmd3BrZHZla3lkb3pqemxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMzM4NzMsImV4cCI6MjA2OTcwOTg3M30.24iundNw4V4t49r-KD8RzLQdVMrU0McD-5xVGzsnfCM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});